title: AuDHS Nord
url: "https://seelenschmutz.github.io"
baseurl: "/audhsnord"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://www.audhs-nord.de"
footer_text: "Impressum"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home" 
   link: "index"
 - name: "Selbsthilfegruppe" 
   link: "shginfo"
 - name: "Impressum" 
   link: "impressum"
