title: Researcher
url: "https://seelenschmutz.github.io"
baseurl: "/audhsnord"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://www.audhs-nord.de"
footer_text: "Impressum"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Selbsthilfegruppe"
   link: "/researcher/"
 # - name: "Resume"
 #  link: "resume.pdf"
 - name: "Impressum"
   link: "contact"
